// Derives src/data/level2-administrative-codes.ts from data/level2-administrative-codes.json.
//
// Emits one named export per country (`level2Admin_US`, `level2Admin_FR`, ...), each a
// readonly array of { value, label, level1Value } objects. Splitting into per-country
// named exports (rather than one big object) is what lets the bundler tree-shake away
// every country that divisions.ts doesn't import, so the full world's worth of divisions
// never reaches the published build.
//
//   value      -> officialCode (ISO 3166-2) or GeoNames code, country prefix stripped
//   label      -> English division name
//   level1Value -> parent level-1 code, country prefix stripped
//
// Run with: bun run gen:level2
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const inFile = resolve(__dirname, "../data/level2-administrative-codes.json");
const outFile = resolve(__dirname, "../src/data/level2-administrative-codes.ts");

type Level2Division = {
  level1AdminCode: string;
  code: string;
  name: string;
  officialCode: string | null;
};

// "US-NY" -> "NY"; leaves codes without a 2-letter country prefix untouched.
function stripPrefix(code: string): string {
  return code.replace(/^[A-Z]{2}-/, "");
}

const level2: Record<string, Level2Division[]> = JSON.parse(await readFile(inFile, "utf8"));

const header = `// AUTO-GENERATED by scripts/gen-level2-codes.ts — do not edit by hand.
// Regenerate with: bun run gen:level2
// One named export per country so unused divisions tree-shake out of the build.

export type Level2DivisionOption = { value: string; label: string; level1Value: string };
`;

const blocks: string[] = [];
for (const code of Object.keys(level2).sort()) {
  const divisions = [...(level2[code] ?? [])].sort((a, b) => a.name.localeCompare(b.name));
  const entries = divisions
    .map((d) => {
      const value = stripPrefix(d.officialCode ?? d.code);
      const level1Value = stripPrefix(d.level1AdminCode);
      return `\t{ value: ${JSON.stringify(value)}, label: ${JSON.stringify(d.name)}, level1Value: ${JSON.stringify(level1Value)} },`;
    })
    .join("\n");
  blocks.push(`export const level2Admin_${code} = [\n${entries}\n] as const satisfies readonly Level2DivisionOption[];`);
}

// src/data/ is excluded from Biome's checks, so we write directly without
// piping through the formatter (the stdin approach used by gen-level1-codes.ts
// fails silently on files this large — ~3 MB — because Biome's stdin formatter
// has no explicit size limit but times out the pipe).
await writeFile(outFile, `${header}\n${blocks.join("\n\n")}\n`);
console.log(
  `wrote ${outFile} (${Object.keys(level2).length} countries, ${Object.values(level2).reduce((s, a) => s + a.length, 0)} entries)`,
);
