// Derives src/data/level1-administrative-codes.ts from data/level1-administrative-codes.json,
// merged with the hand-curated CURATED supplement defined below.
//
// Emits one named export per country (`level1Admin_US`, `level1Admin_FR`, ...), each a
// readonly array of { value, label } ready to drop into a <select>. Splitting
// into per-country named exports (rather than one big object) is what lets the
// bundler tree-shake away every country that countries.ts doesn't import, so
// the full world's worth of divisions never reaches the published build.
//
//   value -> officialCode (ISO 3166-2) or GeoNames code, country prefix stripped
//   label -> English division name
//
// The CURATED constant below adds countries GeoNames ships no admin1 list for
// but which have an official, documented first-level subdivision scheme (e.g.
// SG's 5 ISO 3166-2 CDC districts). Curated divisions are keyed by ISO code and
// merged in per country: a curated division whose `code` matches a GeoNames one
// overrides it; the rest are appended. Add a country by adding an entry here.
//
// Run with: bun run scripts/gen-level1-codes.ts
import { spawn } from 'node:child_process';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { stripPrefix } from './_utils';

// Biome force-excludes src/data, so it won't format these files even via
// `--stdin-file-path` pointing at the real path (an excluded path makes Biome
// echo stdin unchanged). Format the source through stdin under a neutral,
// non-excluded filename — Biome only needs the extension to pick the formatter —
// so it applies the repo's real config before we write.
function formatTs(source: string): Promise<string> {
  return new Promise((resolvePromise, reject) => {
    const child = spawn('bunx', ['biome', 'format', '--stdin-file-path=gen-output.ts']);
    let out = '';
    let err = '';
    child.stdout.on('data', (d) => {
      out += d;
    });
    child.stderr.on('data', (d) => {
      err += d;
    });
    child.on('error', reject);
    child.on('close', (code) => (code === 0 ? resolvePromise(out) : reject(new Error(err || `biome exited ${code}`))));
    child.stdin.end(source);
  });
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const inFile = resolve(__dirname, '../data/level1-administrative-codes.json');
const outFile = resolve(__dirname, '../src/data/level1-administrative-codes.ts');

type Division = {
  code: string;
  name: string;
  officialCode: string | null;
};

// Hand-curated level-1 divisions for countries GeoNames ships no admin1 list
// for, but which have an official ISO 3166-2 subdivision scheme. Keyed by
// alpha-2 code; same shape as the GeoNames source. Add a country here to have
// it generated alongside the rest.
const CURATED: Record<string, Division[]> = {
  // Singapore — 5 Community Development Council (CDC) districts (ISO 3166-2:SG).
  // GeoNames omits SG because Singapore addresses by postal code, not district.
  SG: [
    { code: 'SG-01', name: 'Central Singapore', officialCode: 'SG-01' },
    { code: 'SG-02', name: 'North East', officialCode: 'SG-02' },
    { code: 'SG-03', name: 'North West', officialCode: 'SG-03' },
    { code: 'SG-04', name: 'South East', officialCode: 'SG-04' },
    { code: 'SG-05', name: 'South West', officialCode: 'SG-05' },
  ],
};

const level1: Record<string, Division[]> = JSON.parse(await readFile(inFile, 'utf8'));

// Merge the curated supplement into the GeoNames data, per country. A curated
// division whose `code` matches an existing GeoNames one replaces it (so a
// curated fix wins); every other curated division is appended. Countries absent
// from GeoNames (e.g. SG) are added wholesale.
for (const [countryCode, divisions] of Object.entries(CURATED)) {
  const existing = level1[countryCode] ?? [];
  const byCountryCode = new Map(existing.map((d) => [d.code, d]));
  for (const d of divisions) byCountryCode.set(d.code, d);
  level1[countryCode] = [...byCountryCode.values()];
}

const header = `// AUTO-GENERATED by scripts/gen-level1-codes.ts — do not edit by hand.
// Regenerate with: bun run gen:level1
// One named export per country so unused divisions tree-shake out of the build.

export type AdministrativeDivisionOption = { value: string; label: string };
`;

const blocks: string[] = [];
for (const code of Object.keys(level1).sort((first, second) => first.localeCompare(second, 'en', { sensitivity: 'base' }))) {
  const divisions = [...(level1[code] ?? [])].sort((a, b) => a.name.localeCompare(b.name));
  const entries = divisions
    .map((d) => {
      const value = stripPrefix(d.officialCode ?? d.code);
      return `\t{ value: ${JSON.stringify(value)}, label: ${JSON.stringify(d.name)} },`;
    })
    .join('\n');
  blocks.push(`export const level1Admin_${code} = [\n${entries}\n] as const satisfies readonly AdministrativeDivisionOption[];`);
}

await writeFile(outFile, await formatTs(`${header}\n${blocks.join('\n\n')}\n`));
const curatedCount = Object.keys(CURATED).length;
console.log(`wrote ${outFile} (${Object.keys(level1).length} countries, ${curatedCount} from curated supplement)`);
