// Level-2 administrative division option lists, sourced from
// data/level2-administrative-codes.json via codegen (scripts/gen-level2-codes.ts).
// Each country is a separate named export so the bundler tree-shakes away every
// country that isn't imported here — the full world's worth of divisions never
// reaches the published build for an app that only needs one country.

import type { CountryLocalNames, DivisionLocalNames } from './data/administrative-local-names';
import {
  localNames_AD,
  localNames_AE,
  localNames_AF,
  localNames_AG,
  localNames_AL,
  localNames_AM,
  localNames_AO,
  localNames_AR,
  localNames_AS,
  localNames_AT,
  localNames_AU,
  localNames_AX,
  localNames_AZ,
  localNames_BA,
  localNames_BB,
  localNames_BD,
  localNames_BE,
  localNames_BF,
  localNames_BG,
  localNames_BH,
  localNames_BI,
  localNames_BJ,
  localNames_BM,
  localNames_BN,
  localNames_BO,
  localNames_BQ,
  localNames_BR,
  localNames_BS,
  localNames_BT,
  localNames_BW,
  localNames_BY,
  localNames_BZ,
  localNames_CA,
  localNames_CD,
  localNames_CF,
  localNames_CG,
  localNames_CH,
  localNames_CI,
  localNames_CL,
  localNames_CM,
  localNames_CN,
  localNames_CO,
  localNames_CR,
  localNames_CU,
  localNames_CV,
  localNames_CY,
  localNames_CZ,
  localNames_DE,
  localNames_DJ,
  localNames_DK,
  localNames_DM,
  localNames_DO,
  localNames_DZ,
  localNames_EC,
  localNames_EE,
  localNames_EG,
  localNames_ER,
  localNames_ES,
  localNames_ET,
  localNames_FI,
  localNames_FJ,
  localNames_FM,
  localNames_FO,
  localNames_FR,
  localNames_GA,
  localNames_GB,
  localNames_GD,
  localNames_GE,
  localNames_GF,
  localNames_GG,
  localNames_GH,
  localNames_GL,
  localNames_GM,
  localNames_GN,
  localNames_GP,
  localNames_GQ,
  localNames_GR,
  localNames_GT,
  localNames_GU,
  localNames_GW,
  localNames_GY,
  localNames_HK,
  localNames_HN,
  localNames_HR,
  localNames_HT,
  localNames_HU,
  localNames_ID,
  localNames_IE,
  localNames_IL,
  localNames_IM,
  localNames_IN,
  localNames_IQ,
  localNames_IR,
  localNames_IS,
  localNames_IT,
  localNames_JE,
  localNames_JM,
  localNames_JO,
  localNames_JP,
  localNames_KE,
  localNames_KG,
  localNames_KH,
  localNames_KI,
  localNames_KM,
  localNames_KN,
  localNames_KP,
  localNames_KR,
  localNames_KW,
  localNames_KZ,
  localNames_LA,
  localNames_LB,
  localNames_LC,
  localNames_LI,
  localNames_LK,
  localNames_LR,
  localNames_LS,
  localNames_LT,
  localNames_LU,
  localNames_LV,
  localNames_LY,
  localNames_MA,
  localNames_MC,
  localNames_MD,
  localNames_ME,
  localNames_MG,
  localNames_MH,
  localNames_MK,
  localNames_ML,
  localNames_MM,
  localNames_MN,
  localNames_MO,
  localNames_MP,
  localNames_MQ,
  localNames_MR,
  localNames_MT,
  localNames_MU,
  localNames_MV,
  localNames_MW,
  localNames_MX,
  localNames_MY,
  localNames_MZ,
  localNames_NA,
  localNames_NC,
  localNames_NE,
  localNames_NG,
  localNames_NI,
  localNames_NL,
  localNames_NO,
  localNames_NP,
  localNames_NR,
  localNames_NZ,
  localNames_OM,
  localNames_PA,
  localNames_PE,
  localNames_PF,
  localNames_PG,
  localNames_PH,
  localNames_PK,
  localNames_PL,
  localNames_PR,
  localNames_PS,
  localNames_PT,
  localNames_PW,
  localNames_PY,
  localNames_QA,
  localNames_RE,
  localNames_RO,
  localNames_RS,
  localNames_RU,
  localNames_RW,
  localNames_SA,
  localNames_SB,
  localNames_SC,
  localNames_SD,
  localNames_SE,
  localNames_SH,
  localNames_SI,
  localNames_SJ,
  localNames_SK,
  localNames_SL,
  localNames_SM,
  localNames_SN,
  localNames_SO,
  localNames_SR,
  localNames_SS,
  localNames_ST,
  localNames_SV,
  localNames_SY,
  localNames_SZ,
  localNames_TD,
  localNames_TF,
  localNames_TG,
  localNames_TH,
  localNames_TJ,
  localNames_TK,
  localNames_TL,
  localNames_TM,
  localNames_TN,
  localNames_TO,
  localNames_TR,
  localNames_TT,
  localNames_TV,
  localNames_TW,
  localNames_TZ,
  localNames_UA,
  localNames_UG,
  localNames_UM,
  localNames_US,
  localNames_UY,
  localNames_UZ,
  localNames_VC,
  localNames_VE,
  localNames_VI,
  localNames_VN,
  localNames_VU,
  localNames_WF,
  localNames_WS,
  localNames_XK,
  localNames_YE,
  localNames_YT,
  localNames_ZA,
  localNames_ZM,
  localNames_ZW,
} from './data/administrative-local-names';
import { type CountryCode, isCountryCode } from './data/countries';
import type { Level2DivisionOption } from './data/level2-administrative-codes';
import {
  level2Admin_AE,
  level2Admin_AF,
  level2Admin_AL,
  level2Admin_AM,
  level2Admin_AO,
  level2Admin_AR,
  level2Admin_AS,
  level2Admin_AT,
  level2Admin_AU,
  level2Admin_AX,
  level2Admin_AZ,
  level2Admin_BA,
  level2Admin_BD,
  level2Admin_BE,
  level2Admin_BF,
  level2Admin_BG,
  level2Admin_BI,
  level2Admin_BJ,
  level2Admin_BN,
  level2Admin_BO,
  level2Admin_BR,
  level2Admin_BT,
  level2Admin_BW,
  level2Admin_BY,
  level2Admin_BZ,
  level2Admin_CA,
  level2Admin_CD,
  level2Admin_CF,
  level2Admin_CG,
  level2Admin_CH,
  level2Admin_CI,
  level2Admin_CK,
  level2Admin_CL,
  level2Admin_CM,
  level2Admin_CN,
  level2Admin_CO,
  level2Admin_CR,
  level2Admin_CU,
  level2Admin_CV,
  level2Admin_CY,
  level2Admin_CZ,
  level2Admin_DE,
  level2Admin_DJ,
  level2Admin_DK,
  level2Admin_DO,
  level2Admin_DZ,
  level2Admin_EC,
  level2Admin_EE,
  level2Admin_EG,
  level2Admin_ER,
  level2Admin_ES,
  level2Admin_ET,
  level2Admin_FI,
  level2Admin_FJ,
  level2Admin_FM,
  level2Admin_FO,
  level2Admin_FR,
  level2Admin_GA,
  level2Admin_GB,
  level2Admin_GE,
  level2Admin_GF,
  level2Admin_GH,
  level2Admin_GL,
  level2Admin_GM,
  level2Admin_GN,
  level2Admin_GP,
  level2Admin_GQ,
  level2Admin_GR,
  level2Admin_GT,
  level2Admin_GW,
  level2Admin_HN,
  level2Admin_HR,
  level2Admin_HT,
  level2Admin_HU,
  level2Admin_ID,
  level2Admin_IE,
  level2Admin_IL,
  level2Admin_IN,
  level2Admin_IQ,
  level2Admin_IR,
  level2Admin_IS,
  level2Admin_IT,
  level2Admin_JM,
  level2Admin_JO,
  level2Admin_JP,
  level2Admin_KE,
  level2Admin_KG,
  level2Admin_KH,
  level2Admin_KI,
  level2Admin_KP,
  level2Admin_KR,
  level2Admin_KW,
  level2Admin_KZ,
  level2Admin_LA,
  level2Admin_LB,
  level2Admin_LC,
  level2Admin_LK,
  level2Admin_LR,
  level2Admin_LS,
  level2Admin_LT,
  level2Admin_LU,
  level2Admin_LV,
  level2Admin_LY,
  level2Admin_MA,
  level2Admin_MG,
  level2Admin_MK,
  level2Admin_ML,
  level2Admin_MM,
  level2Admin_MN,
  level2Admin_MP,
  level2Admin_MQ,
  level2Admin_MR,
  level2Admin_MW,
  level2Admin_MX,
  level2Admin_MY,
  level2Admin_MZ,
  level2Admin_NA,
  level2Admin_NC,
  level2Admin_NE,
  level2Admin_NG,
  level2Admin_NI,
  level2Admin_NL,
  level2Admin_NO,
  level2Admin_NP,
  level2Admin_NZ,
  level2Admin_OM,
  level2Admin_PA,
  level2Admin_PE,
  level2Admin_PF,
  level2Admin_PG,
  level2Admin_PH,
  level2Admin_PK,
  level2Admin_PL,
  level2Admin_PR,
  level2Admin_PS,
  level2Admin_PT,
  level2Admin_PW,
  level2Admin_PY,
  level2Admin_RE,
  level2Admin_RO,
  level2Admin_RS,
  level2Admin_RU,
  level2Admin_RW,
  level2Admin_SA,
  level2Admin_SB,
  level2Admin_SD,
  level2Admin_SE,
  level2Admin_SH,
  level2Admin_SI,
  level2Admin_SJ,
  level2Admin_SK,
  level2Admin_SL,
  level2Admin_SN,
  level2Admin_SO,
  level2Admin_SR,
  level2Admin_SS,
  level2Admin_ST,
  level2Admin_SV,
  level2Admin_SY,
  level2Admin_SZ,
  level2Admin_TD,
  level2Admin_TF,
  level2Admin_TG,
  level2Admin_TH,
  level2Admin_TJ,
  level2Admin_TL,
  level2Admin_TM,
  level2Admin_TN,
  level2Admin_TO,
  level2Admin_TR,
  level2Admin_TT,
  level2Admin_TV,
  level2Admin_TW,
  level2Admin_TZ,
  level2Admin_UA,
  level2Admin_UG,
  level2Admin_US,
  level2Admin_UY,
  level2Admin_UZ,
  level2Admin_VE,
  level2Admin_VI,
  level2Admin_VN,
  level2Admin_WF,
  level2Admin_WS,
  level2Admin_XK,
  level2Admin_YE,
  level2Admin_ZA,
  level2Admin_ZM,
  level2Admin_ZW,
} from './data/level2-administrative-codes';

// Level-2 <select> option lists, one entry per country that has division data.
// The same per-country named-export pattern as LEVEL1_OPTIONS in address.ts:
// only the countries explicitly imported above are bundled; unused ones
// tree-shake out so a consumer that imports only `FR` gets just FR's data.
const LEVEL2_OPTIONS: Partial<Record<CountryCode, readonly Level2DivisionOption[]>> = {
  AE: level2Admin_AE,
  AF: level2Admin_AF,
  AL: level2Admin_AL,
  AM: level2Admin_AM,
  AO: level2Admin_AO,
  AR: level2Admin_AR,
  AS: level2Admin_AS,
  AT: level2Admin_AT,
  AU: level2Admin_AU,
  AX: level2Admin_AX,
  AZ: level2Admin_AZ,
  BA: level2Admin_BA,
  BD: level2Admin_BD,
  BE: level2Admin_BE,
  BF: level2Admin_BF,
  BG: level2Admin_BG,
  BI: level2Admin_BI,
  BJ: level2Admin_BJ,
  BN: level2Admin_BN,
  BO: level2Admin_BO,
  BR: level2Admin_BR,
  BT: level2Admin_BT,
  BW: level2Admin_BW,
  BY: level2Admin_BY,
  BZ: level2Admin_BZ,
  CA: level2Admin_CA,
  CD: level2Admin_CD,
  CF: level2Admin_CF,
  CG: level2Admin_CG,
  CH: level2Admin_CH,
  CI: level2Admin_CI,
  CK: level2Admin_CK,
  CL: level2Admin_CL,
  CM: level2Admin_CM,
  CN: level2Admin_CN,
  CO: level2Admin_CO,
  CR: level2Admin_CR,
  CU: level2Admin_CU,
  CV: level2Admin_CV,
  CY: level2Admin_CY,
  CZ: level2Admin_CZ,
  DE: level2Admin_DE,
  DJ: level2Admin_DJ,
  DK: level2Admin_DK,
  DO: level2Admin_DO,
  DZ: level2Admin_DZ,
  EC: level2Admin_EC,
  EE: level2Admin_EE,
  EG: level2Admin_EG,
  ER: level2Admin_ER,
  ES: level2Admin_ES,
  ET: level2Admin_ET,
  FI: level2Admin_FI,
  FJ: level2Admin_FJ,
  FM: level2Admin_FM,
  FO: level2Admin_FO,
  FR: level2Admin_FR,
  GA: level2Admin_GA,
  GB: level2Admin_GB,
  GE: level2Admin_GE,
  GF: level2Admin_GF,
  GH: level2Admin_GH,
  GL: level2Admin_GL,
  GM: level2Admin_GM,
  GN: level2Admin_GN,
  GP: level2Admin_GP,
  GQ: level2Admin_GQ,
  GR: level2Admin_GR,
  GT: level2Admin_GT,
  GW: level2Admin_GW,
  HN: level2Admin_HN,
  HR: level2Admin_HR,
  HT: level2Admin_HT,
  HU: level2Admin_HU,
  ID: level2Admin_ID,
  IE: level2Admin_IE,
  IL: level2Admin_IL,
  IN: level2Admin_IN,
  IQ: level2Admin_IQ,
  IR: level2Admin_IR,
  IS: level2Admin_IS,
  IT: level2Admin_IT,
  JM: level2Admin_JM,
  JO: level2Admin_JO,
  JP: level2Admin_JP,
  KE: level2Admin_KE,
  KG: level2Admin_KG,
  KH: level2Admin_KH,
  KI: level2Admin_KI,
  KP: level2Admin_KP,
  KR: level2Admin_KR,
  KW: level2Admin_KW,
  KZ: level2Admin_KZ,
  LA: level2Admin_LA,
  LB: level2Admin_LB,
  LC: level2Admin_LC,
  LK: level2Admin_LK,
  LR: level2Admin_LR,
  LS: level2Admin_LS,
  LT: level2Admin_LT,
  LU: level2Admin_LU,
  LV: level2Admin_LV,
  LY: level2Admin_LY,
  MA: level2Admin_MA,
  MG: level2Admin_MG,
  MK: level2Admin_MK,
  ML: level2Admin_ML,
  MM: level2Admin_MM,
  MN: level2Admin_MN,
  MP: level2Admin_MP,
  MQ: level2Admin_MQ,
  MR: level2Admin_MR,
  MW: level2Admin_MW,
  MX: level2Admin_MX,
  MY: level2Admin_MY,
  MZ: level2Admin_MZ,
  NA: level2Admin_NA,
  NC: level2Admin_NC,
  NE: level2Admin_NE,
  NG: level2Admin_NG,
  NI: level2Admin_NI,
  NL: level2Admin_NL,
  NO: level2Admin_NO,
  NP: level2Admin_NP,
  NZ: level2Admin_NZ,
  OM: level2Admin_OM,
  PA: level2Admin_PA,
  PE: level2Admin_PE,
  PF: level2Admin_PF,
  PG: level2Admin_PG,
  PH: level2Admin_PH,
  PK: level2Admin_PK,
  PL: level2Admin_PL,
  PR: level2Admin_PR,
  PS: level2Admin_PS,
  PT: level2Admin_PT,
  PW: level2Admin_PW,
  PY: level2Admin_PY,
  RE: level2Admin_RE,
  RO: level2Admin_RO,
  RS: level2Admin_RS,
  RU: level2Admin_RU,
  RW: level2Admin_RW,
  SA: level2Admin_SA,
  SB: level2Admin_SB,
  SD: level2Admin_SD,
  SE: level2Admin_SE,
  SH: level2Admin_SH,
  SI: level2Admin_SI,
  SJ: level2Admin_SJ,
  SK: level2Admin_SK,
  SL: level2Admin_SL,
  SN: level2Admin_SN,
  SO: level2Admin_SO,
  SR: level2Admin_SR,
  SS: level2Admin_SS,
  ST: level2Admin_ST,
  SV: level2Admin_SV,
  SY: level2Admin_SY,
  SZ: level2Admin_SZ,
  TD: level2Admin_TD,
  TF: level2Admin_TF,
  TG: level2Admin_TG,
  TH: level2Admin_TH,
  TJ: level2Admin_TJ,
  TL: level2Admin_TL,
  TM: level2Admin_TM,
  TN: level2Admin_TN,
  TO: level2Admin_TO,
  TR: level2Admin_TR,
  TT: level2Admin_TT,
  TV: level2Admin_TV,
  TW: level2Admin_TW,
  TZ: level2Admin_TZ,
  UA: level2Admin_UA,
  UG: level2Admin_UG,
  US: level2Admin_US,
  UY: level2Admin_UY,
  UZ: level2Admin_UZ,
  VE: level2Admin_VE,
  VI: level2Admin_VI,
  VN: level2Admin_VN,
  WF: level2Admin_WF,
  WS: level2Admin_WS,
  XK: level2Admin_XK,
  YE: level2Admin_YE,
  ZA: level2Admin_ZA,
  ZM: level2Admin_ZM,
  ZW: level2Admin_ZW,
};

/**
 * Returns all level-2 division options for the given country code.
 *
 * When `level1` is supplied, only the divisions whose parent level-1 value
 * matches are returned — useful for cascading `<select>` menus where the
 * level-2 list narrows after the user picks a level-1 region.
 *
 * Returns an empty array for any country without level-2 data or an
 * unrecognised country code.
 *
 * @example
 * // All counties in the United States
 * getLevel2Options("US");
 *
 * @example
 * // Only New York State counties
 * getLevel2Options("US", "NY");
 */
function getLevel2Options(country: string, level1?: string): readonly Level2DivisionOption[] {
  const code = isCountryCode(country) ? country : null;
  if (!code) return [];
  const all = LEVEL2_OPTIONS[code] ?? [];
  if (level1 === undefined) return all;
  return all.filter((d) => d.level1Value === level1);
}

/**
 * Whether level-2 division data is available for the given country code.
 */
function hasLevel2Options(country: string): boolean {
  const code = isCountryCode(country) ? country : null;
  if (!code) return false;
  return (LEVEL2_OPTIONS[code]?.length ?? 0) > 0;
}

// Localized division names, one entry per country that has at least one
// localized division. Same per-country named-export / lookup-map pattern as
// LEVEL2_OPTIONS above: only countries referenced here are bundled, so a
// consumer importing a single country tree-shakes the rest away.
const LOCAL_NAMES: Partial<Record<CountryCode, CountryLocalNames>> = {
  AD: localNames_AD,
  AE: localNames_AE,
  AF: localNames_AF,
  AG: localNames_AG,
  AL: localNames_AL,
  AM: localNames_AM,
  AO: localNames_AO,
  AR: localNames_AR,
  AS: localNames_AS,
  AT: localNames_AT,
  AU: localNames_AU,
  AX: localNames_AX,
  AZ: localNames_AZ,
  BA: localNames_BA,
  BB: localNames_BB,
  BD: localNames_BD,
  BE: localNames_BE,
  BF: localNames_BF,
  BG: localNames_BG,
  BH: localNames_BH,
  BI: localNames_BI,
  BJ: localNames_BJ,
  BM: localNames_BM,
  BN: localNames_BN,
  BO: localNames_BO,
  BQ: localNames_BQ,
  BR: localNames_BR,
  BS: localNames_BS,
  BT: localNames_BT,
  BW: localNames_BW,
  BY: localNames_BY,
  BZ: localNames_BZ,
  CA: localNames_CA,
  CD: localNames_CD,
  CF: localNames_CF,
  CG: localNames_CG,
  CH: localNames_CH,
  CI: localNames_CI,
  CL: localNames_CL,
  CM: localNames_CM,
  CN: localNames_CN,
  CO: localNames_CO,
  CR: localNames_CR,
  CU: localNames_CU,
  CV: localNames_CV,
  CY: localNames_CY,
  CZ: localNames_CZ,
  DE: localNames_DE,
  DJ: localNames_DJ,
  DK: localNames_DK,
  DM: localNames_DM,
  DO: localNames_DO,
  DZ: localNames_DZ,
  EC: localNames_EC,
  EE: localNames_EE,
  EG: localNames_EG,
  ER: localNames_ER,
  ES: localNames_ES,
  ET: localNames_ET,
  FI: localNames_FI,
  FJ: localNames_FJ,
  FM: localNames_FM,
  FO: localNames_FO,
  FR: localNames_FR,
  GA: localNames_GA,
  GB: localNames_GB,
  GD: localNames_GD,
  GE: localNames_GE,
  GF: localNames_GF,
  GG: localNames_GG,
  GH: localNames_GH,
  GL: localNames_GL,
  GM: localNames_GM,
  GN: localNames_GN,
  GP: localNames_GP,
  GQ: localNames_GQ,
  GR: localNames_GR,
  GT: localNames_GT,
  GU: localNames_GU,
  GW: localNames_GW,
  GY: localNames_GY,
  HK: localNames_HK,
  HN: localNames_HN,
  HR: localNames_HR,
  HT: localNames_HT,
  HU: localNames_HU,
  ID: localNames_ID,
  IE: localNames_IE,
  IL: localNames_IL,
  IM: localNames_IM,
  IN: localNames_IN,
  IQ: localNames_IQ,
  IR: localNames_IR,
  IS: localNames_IS,
  IT: localNames_IT,
  JE: localNames_JE,
  JM: localNames_JM,
  JO: localNames_JO,
  JP: localNames_JP,
  KE: localNames_KE,
  KG: localNames_KG,
  KH: localNames_KH,
  KI: localNames_KI,
  KM: localNames_KM,
  KN: localNames_KN,
  KP: localNames_KP,
  KR: localNames_KR,
  KW: localNames_KW,
  KZ: localNames_KZ,
  LA: localNames_LA,
  LB: localNames_LB,
  LC: localNames_LC,
  LI: localNames_LI,
  LK: localNames_LK,
  LR: localNames_LR,
  LS: localNames_LS,
  LT: localNames_LT,
  LU: localNames_LU,
  LV: localNames_LV,
  LY: localNames_LY,
  MA: localNames_MA,
  MC: localNames_MC,
  MD: localNames_MD,
  ME: localNames_ME,
  MG: localNames_MG,
  MH: localNames_MH,
  MK: localNames_MK,
  ML: localNames_ML,
  MM: localNames_MM,
  MN: localNames_MN,
  MO: localNames_MO,
  MP: localNames_MP,
  MQ: localNames_MQ,
  MR: localNames_MR,
  MT: localNames_MT,
  MU: localNames_MU,
  MV: localNames_MV,
  MW: localNames_MW,
  MX: localNames_MX,
  MY: localNames_MY,
  MZ: localNames_MZ,
  NA: localNames_NA,
  NC: localNames_NC,
  NE: localNames_NE,
  NG: localNames_NG,
  NI: localNames_NI,
  NL: localNames_NL,
  NO: localNames_NO,
  NP: localNames_NP,
  NR: localNames_NR,
  NZ: localNames_NZ,
  OM: localNames_OM,
  PA: localNames_PA,
  PE: localNames_PE,
  PF: localNames_PF,
  PG: localNames_PG,
  PH: localNames_PH,
  PK: localNames_PK,
  PL: localNames_PL,
  PR: localNames_PR,
  PS: localNames_PS,
  PT: localNames_PT,
  PW: localNames_PW,
  PY: localNames_PY,
  QA: localNames_QA,
  RE: localNames_RE,
  RO: localNames_RO,
  RS: localNames_RS,
  RU: localNames_RU,
  RW: localNames_RW,
  SA: localNames_SA,
  SB: localNames_SB,
  SC: localNames_SC,
  SD: localNames_SD,
  SE: localNames_SE,
  SH: localNames_SH,
  SI: localNames_SI,
  SJ: localNames_SJ,
  SK: localNames_SK,
  SL: localNames_SL,
  SM: localNames_SM,
  SN: localNames_SN,
  SO: localNames_SO,
  SR: localNames_SR,
  SS: localNames_SS,
  ST: localNames_ST,
  SV: localNames_SV,
  SY: localNames_SY,
  SZ: localNames_SZ,
  TD: localNames_TD,
  TF: localNames_TF,
  TG: localNames_TG,
  TH: localNames_TH,
  TJ: localNames_TJ,
  TK: localNames_TK,
  TL: localNames_TL,
  TM: localNames_TM,
  TN: localNames_TN,
  TO: localNames_TO,
  TR: localNames_TR,
  TT: localNames_TT,
  TV: localNames_TV,
  TW: localNames_TW,
  TZ: localNames_TZ,
  UA: localNames_UA,
  UG: localNames_UG,
  UM: localNames_UM,
  US: localNames_US,
  UY: localNames_UY,
  UZ: localNames_UZ,
  VC: localNames_VC,
  VE: localNames_VE,
  VI: localNames_VI,
  VN: localNames_VN,
  VU: localNames_VU,
  WF: localNames_WF,
  WS: localNames_WS,
  XK: localNames_XK,
  YE: localNames_YE,
  YT: localNames_YT,
  ZA: localNames_ZA,
  ZM: localNames_ZM,
  ZW: localNames_ZW,
};

function countryLocalNames(country: string): CountryLocalNames | undefined {
  const code = isCountryCode(country) ? country : null;
  if (!code) return;
  return LOCAL_NAMES[code];
}

/**
 * Returns the localized names of a level-1 division, keyed by language code
 * (e.g. `{ de: "Zürich", fr: "Zurich", it: "Zurigo", rm: "Turitg" }`), or
 * `undefined` when the country, the division, or any localized name is unknown.
 *
 * `level1Value` is the same `value` the level-1 option lists expose (from
 * `resolveAddressField(code, "level1").options`), i.e. the value held after a
 * `<select>`.
 *
 * @example
 * getLevel1LocalNames("CH", "ZH"); // { de: "Zürich", fr: "Zurich", it: "Zurigo", rm: "Turitg" }
 */
function getLevel1LocalNames(country: string, level1Value: string): DivisionLocalNames | undefined {
  return countryLocalNames(country)?.level1[level1Value];
}

/**
 * Returns the localized names of a level-2 division, keyed by language code, or
 * `undefined` when the country, the division, or any localized name is unknown.
 *
 * `level1Value` / `level2Value` are the same values the option lists expose:
 * `level2Value` is `getLevel2Options(country, level1Value)[n].value` and
 * `level1Value` is its `.level1Value`. Both are required because a level-2
 * value is only unique within its parent level-1 division.
 *
 * @example
 * getLevel2LocalNames("FR", "84", "01"); // { fr: "Ain", oc: "Ain", ... }
 */
function getLevel2LocalNames(country: string, level1Value: string, level2Value: string): DivisionLocalNames | undefined {
  return countryLocalNames(country)?.level2[level1Value]?.[level2Value];
}

/**
 * Resolves a single localized level-1 division name for the first of
 * `languages` that has one, or `undefined` if none match.
 *
 * @example
 * getLevel1LocalName("DE", "BY", ["fr", "de"]); // "Bayern" (no French name, falls back to German)
 */
function getLevel1LocalName(country: string, level1Value: string, languages: string | readonly string[]): string | undefined {
  return pickLocalName(getLevel1LocalNames(country, level1Value), languages);
}

/**
 * Resolves a single localized level-2 division name for the first of
 * `languages` that has one, or `undefined` if none match.
 *
 * @example
 * getLevel2LocalName("FR", "84", "01", ["oc", "fr"]); // "Ain"
 */
function getLevel2LocalName(
  country: string,
  level1Value: string,
  level2Value: string,
  languages: string | readonly string[],
): string | undefined {
  return pickLocalName(getLevel2LocalNames(country, level1Value, level2Value), languages);
}

/**
 * Whether localized division names are available for the given country code.
 */
function hasLocalNames(country: string): boolean {
  const names = countryLocalNames(country);
  if (!names) return false;
  return Object.keys(names.level1).length > 0 || Object.keys(names.level2).length > 0;
}

/**
 * Picks the localized name for the first language in `languages` that has one.
 * Accepts a single language code or an ordered preference list; returns
 * `undefined` when `names` is absent or none of the languages match.
 */
function pickLocalName(names: DivisionLocalNames | undefined, languages: string | readonly string[]): string | undefined {
  if (!names) return;
  const prefs = typeof languages === 'string' ? [languages] : languages;
  for (const lang of prefs) {
    const name = names[lang];
    if (name !== undefined) return name;
  }
}

export type { CountryLocalNames, DivisionLocalNames } from './data/administrative-local-names';
export type { Level2DivisionOption } from './data/level2-administrative-codes';

export {
  getLevel1LocalName,
  getLevel1LocalNames,
  getLevel2LocalName,
  getLevel2LocalNames,
  getLevel2Options,
  hasLevel2Options,
  hasLocalNames,
  pickLocalName,
};
